### ISSUE TITLE
Throws in MSIE 6: 'Array.prototype.map' is null or not an object

### ISSUE THREAD

**Issue by mk-pmb** [node-browser-compat/atob#10]
Affects current master = 2.0.3

I suggest to migrate to my `buf2binstr` function from https://gist.github.com/mk-pmb/5e50c870ee0c055e0abb8b4f474536a0#file-binstr-cmp-js-L37 .

I'm working on a PR to add browser tests, so if you agree I'll fix it in that PR.

**Comment by coolaj86** [comment]
I'd suggest using https://github.com/es-shims/es5-shim

I'm all for old school, but MSIE6 support was dropped a long, long time ago.

What's your use case?

**Comment by mk-pmb** [comment]
Meanwhile I forgot the use case, so I probably solved it some other way.

**Comment by mk-pmb** [comment]
That said, let's declare which browsers are meant to be supported.
