### ISSUE TITLE
window.atob fallback?

### ISSUE THREAD

**Issue by tmcw** [node-browser-compat/atob#2]
Would you be open to a pull request that made it so that if you include this package via browserify, it'd include a simple `module.exports = window.atob;` file so that the Buffer polyfill wouldn't be included?

**Comment by coolaj86** [comment]
Sure.

**Comment by coolaj86** [comment]
Hey check out versions 1.2.0 and 2.0.0 and see if either of those work for you

**Comment by tmcw** [comment]
Fixed in https://github.com/node-browser-compat/atob/pull/3
