### ISSUE TITLE
new Buffer() is deprecated

### ISSUE THREAD

**Issue by stevenvachon** [node-browser-compat/atob#8]
... and even removed in Node 8.0

Use:
```js
Buffer.from()
```

**Comment by mk-pmb** [comment]
Fix is included in PR #9.

**Comment by coolaj86** [comment]
npm handle? I'll add you so you can contrib and push.

**Comment by mk-pmb** [comment]
Same as here, thanks!

**Comment by coolaj86** [comment]
Moved to https://git.coolaj86.com/coolaj86/atob.js
